### ISSUE TITLE
表哥能不能编译个win版的？

### ISSUE THREAD

**Issue by maybe-why-not** [myvyang/chromium_for_spider#1]
表哥能不能编译个win版的？
![image](https://user-images.githubusercontent.com/29968903/65818605-872ced00-e245-11e9-9814-7c4c6c69e349.png)
还有window.eventNames和window.eventNodes要怎么用，示例html看的我一脸懵逼。

**Comment by myvyang** [comment]
不好意思，我没有windows编译环境。

如果有热心观众能够编译出来，欢迎联系我添加到release中。

**Comment by myvyang** [comment]
> 还有window.eventNames和window.eventNodes要怎么用，示例html看的我一脸懵逼。

通过puppeteer在页面内执行JS即可获取到对应的值。
