### ISSUE TITLE
关于ajax请求的链接

### ISSUE THREAD

**Issue by akitaTian** [myvyang/chromium_for_spider#3]
作者好， 感谢提供的源码diff， 有个问题咨询下

当我点击ajax请求的链接时， 也会被当作导航处理， 这个要怎么解决？ 谢谢

**Comment by myvyang** [comment]
有示例代码不，方便理解。

**Comment by akitaTian** [comment]
> 有示例代码不，方便理解。

http://testphp.vulnweb.com/AJAX/index.php 这个网站 点击 artists元素加载内容， 但是在这个定制的浏览器中是被当作导航了， 
调用到了StartNavigation这个函数了， 
javascript:loadSomething('artists.php')这个写法会首先导航么

**Comment by akitaTian** [comment]
> > 有示例代码不，方便理解。
> 
> http://testphp.vulnweb.com/AJAX/index.php 这个网站 点击 artists元素加载内容， 但是在这个定制的浏览器中是被当作导航了，
> 调用到了StartNavigation这个函数了，
> javascript:loadSomething('artists.php')这个写法会首先导航么

我看了下chromium的源码 应该是在导航过程中对这种href嵌入js脚本的行为做处理的， 多谢了
